version: "2"
services:
  devopstalks:
    container_name: devopstalks
    restart: always
    build: .
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
